services:
  db:
    image: mysql:8.0
    container_name: workshop_b3_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:-rootpassword}"
      MYSQL_DATABASE: "${MYSQL_DATABASE:-resource_management}"
      MYSQL_USER: "${MYSQL_USER:-api_user}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD:-apipassword}"
    volumes:
      - db_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "${DB_PORT:-3307}:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: workshop_b3_api
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./public/uploads:/app/public/uploads
    ports:
      - "${API_PORT:-3001}:3001"
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: "${MYSQL_USER:-api_user}"
      DB_PASSWORD: "${MYSQL_PASSWORD:-apipassword}"
      DB_NAME: "${MYSQL_DATABASE:-resource_management}"
      PORT: 3001
      RUN_SEED: "${RUN_SEED:-false}"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/"]
      timeout: 10s
      retries: 5

volumes:
  db_data:
